### ISSUE TITLE
Base voltage color

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-incubator#40]
* **Do you want to request a *feature* or report a *bug*?**
A new  feature, we need a way to configure in the platform colors corresponding to a base voltage range. 

* **What is the current behavior?**
It does exist so only solution is  to hard code colors which can in reality be different depending of use cases.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

* **What is the expected behavior?**
Is has to be configurable, I would go for a yaml file stored in $HOME/.itools/base-voltages.yml

We need:
 - to define a list of base voltage range
 - each range has a name
 - each range a a color (provided in hexa like #FFFFFFF)
 - each range is  associated to a profile
 - a default profile is speciified

```yaml
baseVoltage:
    - name: "400"
      minValue: 300
      maxValue: 500
      color: #BBBBBBB
      profile: "RTE"
    - name: "225"
      minValue: 180
      maxValue: 300
      color: #AAAAAAA
      profile: "RTE"

default-profile: "RTE"
``` 
A Java API has to be developped to acces this file. Something like:

```java
class BaseVoltageColor {

    List<String> getProfiles() {
    }

    List<String> getBaseVoltageNames(String profile) {
    }

    String getBaseVoltageName(double baseVoltage, String profile) {    
    }
 
    String getColor(String baseVoltageName) {
    }
}

```

* **What is the motivation / use case for changing the behavior?**

Substation diagram, grid map coloration with TSO specificity.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0-SNAPSHOT
  - OS Version: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
